# Generated by Django 3.1 on 2022-01-19 22:36

from django.db import migrations, models
import django.db.models.deletion
import lib.md5


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default=lib.md5.uuid_md5, max_length=32, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('c', 'Canceled'), ('f', 'Finished')], default='f', max_length=1)),
                ('description', models.CharField(max_length=100, null=True)),
                ('cost_no_taxes', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price_no_taxes', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('stock', models.IntegerField(verbose_name='Cantidad')),
                ('min_stock_allowed', models.IntegerField(null=True, verbose_name='Stock minimo permitido')),
                ('is_in_dolar', models.BooleanField(default=False, help_text='Determines if the product cotization is in dolar.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default=lib.md5.uuid_md5, max_length=32, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('c', 'Canceled'), ('f', 'Finished')], default='f', max_length=1)),
                ('name', models.CharField(max_length=50)),
                ('tax_condition', models.CharField(choices=[('rp', 'Responsable Inscripto'), ('sp', 'Monotributista'), ('ex', 'IVA Excento'), ('nr', 'No Alcanzado'), ('fc', 'Consumidor Final')], default='fc', max_length=25)),
                ('cuit', models.CharField(help_text='Personal tax identification number', max_length=15, null=True)),
                ('direction', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('dni', models.PositiveIntegerField(help_text='Personal identification number', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default=lib.md5.uuid_md5, max_length=32, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('c', 'Canceled'), ('f', 'Finished')], default='w', max_length=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default=lib.md5.uuid_md5, max_length=32, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('c', 'Canceled'), ('f', 'Finished')], default='f', max_length=1)),
                ('name', models.CharField(max_length=50)),
                ('tax_condition', models.CharField(choices=[('rp', 'Responsable Inscripto'), ('sp', 'Monotributista'), ('ex', 'IVA Excento'), ('nr', 'No Alcanzado'), ('fc', 'Consumidor Final')], default='fc', max_length=25)),
                ('cuit', models.CharField(help_text='Personal tax identification number', max_length=15, null=True)),
                ('direction', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default=lib.md5.uuid_md5, max_length=32, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('c', 'Canceled'), ('f', 'Finished')], default='w', max_length=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('extra_discount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_discounted', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default=lib.md5.uuid_md5, max_length=32, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('c', 'Canceled'), ('f', 'Finished')], default='f', max_length=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_by_quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField()),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.article')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default=lib.md5.uuid_md5, max_length=32, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('c', 'Canceled'), ('f', 'Finished')], default='w', max_length=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.provider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LossDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default=lib.md5.uuid_md5, max_length=32, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('c', 'Canceled'), ('f', 'Finished')], default='f', max_length=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.article')),
                ('loss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.loss')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default=lib.md5.uuid_md5, max_length=32, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('c', 'Canceled'), ('f', 'Finished')], default='f', max_length=1)),
                ('is_in_dolar', models.BooleanField(default=False, null=True)),
                ('cost_no_taxes', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_by_quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField()),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.article')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.purchase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
