# Generated by Django 3.0.6 on 2020-05-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('seccion', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
