# Generated by Django 3.0.6 on 2020-05-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='seccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
