# Generated by Django 3.0.6 on 2020-06-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20200531_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='codigo',
            field=models.BigIntegerField(unique=True),
        ),
    ]
