# Generated by Django 3.0.6 on 2020-06-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20200606_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
