# Generated by Django 3.0.6 on 2020-06-11 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20200606_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.ArtState')),
            ],
        ),
        migrations.CreateModel(
            name='Perdida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.ArtState')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.ArtState')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='id_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.ArtState'),
        ),
    ]
