# Generated by Django 3.0.6 on 2020-06-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_detalleentrada_porcentaje_ganancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='porcentaje_ganancia',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
