# Generated by Django 3.0.6 on 2020-06-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_article_porcentaje_ganancia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleentrada',
            name='porcentaje_ganancia',
        ),
    ]
