# Generated by Django 3.0.6 on 2020-07-05 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_remove_detalleentrada_porcentaje_ganancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('condicion_iva', models.CharField(max_length=25)),
                ('dni', models.PositiveIntegerField()),
                ('cuit', models.PositiveIntegerField(null=True)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('telefono', models.PositiveIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.Cliente'),
        ),
    ]
