# Generated by Django 3.0.6 on 2020-07-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_auto_20200705_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuit',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
