# Generated by Django 3.0.6 on 2020-07-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_auto_20200706_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='costo_sin_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='precio_sin_iva',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
