# Generated by Django 3.0.6 on 2020-07-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_auto_20200707_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='costo_sin_iva',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='precio_sin_iva',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
