# Generated by Django 3.0.6 on 2020-08-05 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_entrada_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='cliente',
            new_name='proveedor',
        ),
    ]
