# Generated by Django 3.1 on 2020-08-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_auto_20200804_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
