# Generated by Django 3.1 on 2020-08-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_auto_20200812_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
