# Generated by Django 3.1 on 2020-08-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_article_precio_descontado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='pocentaje_descuento',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='precio_descontado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
