# Generated by Django 3.1 on 2020-08-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_auto_20200824_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='pocentaje_descuento',
            new_name='porcentaje_descuento',
        ),
    ]
