# Generated by Django 3.1 on 2020-08-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_auto_20200824_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='precio_descontado',
            new_name='descuento',
        ),
    ]
