# Generated by Django 3.1 on 2020-08-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_auto_20200824_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_con_descuento',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
