# Generated by Django 3.1 on 2020-08-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_auto_20200824_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
    ]
