# Generated by Django 3.1 on 2020-09-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_remove_cliente_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='precio_descontado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
