# Generated by Django 3.1 on 2020-09-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0034_auto_20200904_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='seccion',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
