# Generated by Django 3.1 on 2020-09-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0035_auto_20200907_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
