# Generated by Django 3.1 on 2020-09-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0036_article_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='alarma_stock',
            field=models.IntegerField(null=True, verbose_name='Stock minimo permitido'),
        ),
    ]
