# Generated by Django 3.1 on 2020-09-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0037_article_alarma_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento_adicional',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
