# Generated by Django 3.1 on 2020-09-17 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0038_venta_descuento_adicional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='descuento_adicional',
        ),
    ]
