# Generated by Django 3.1 on 2020-09-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0039_remove_venta_descuento_adicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento_adicional',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
