# Generated by Django 3.1 on 2020-10-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0040_venta_descuento_adicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='condicion_iva',
            field=models.CharField(default='Consumidor Final', max_length=25),
        ),
    ]
