# Generated by Django 3.1 on 2020-10-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0042_article_en_dolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleentrada',
            name='en_dolar',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
