# Generated by Django 3.1 on 2020-10-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0043_detalleentrada_en_dolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='precio_por_cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
