# Generated by Django 3.1 on 2020-11-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0044_detalleventa_precio_por_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleentrada',
            name='costo_por_cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
