# Generated by Django 3.1 on 2021-03-08 12:26

from django.db import migrations

def create_default_states(apps, schema_editor):  
    State = apps.get_model("erp", "ArtState")
    states = ['Active', 'Inactive', 'Deleted']
    for state in states:
        if not State.objects.filter(nombre=state).exists():
            try:
                State.objects.create(nombre=state)
            except:
                print("Imposible create state {}".format(state))
        else:
            print(f"State {state} already exists.")


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0045_detalleentrada_costo_por_cantidad'),
    ]

    operations = [
        migrations.RunPython(create_default_states, migrations.RunPython.noop),
    ]
