# Generated by Django 3.1 on 2022-01-19 22:36

from decimal import Decimal
from django.db import migrations, models
import lib.md5


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioDolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default=lib.md5.uuid_md5, max_length=32, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('c', 'Canceled'), ('f', 'Finished')], default='f', max_length=1)),
                ('oficial_compra', models.DecimalField(decimal_places=2, default=Decimal('103.67'), max_digits=10, null=True)),
                ('oficial_venta', models.DecimalField(decimal_places=2, default=Decimal('109.67'), max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
