# Generated by Django 3.1 on 2020-10-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioDolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficial_compra', models.DecimalField(decimal_places=2, default='77,850', max_digits=10, null=True)),
                ('oficial_venta', models.DecimalField(decimal_places=2, default='83,850', max_digits=10, null=True)),
            ],
        ),
    ]
