# Generated by Django 3.1 on 2020-10-27 23:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciodolar',
            name='oficial_compra',
            field=models.DecimalField(decimal_places=2, default=Decimal('77.890'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='preciodolar',
            name='oficial_venta',
            field=models.DecimalField(decimal_places=2, default=Decimal('83.890'), max_digits=10, null=True),
        ),
    ]
