# Generated by Django 3.1 on 2020-11-10 10:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201027_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciodolar',
            name='oficial_compra',
            field=models.DecimalField(decimal_places=2, default=Decimal('78.950'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='preciodolar',
            name='oficial_venta',
            field=models.DecimalField(decimal_places=2, default=Decimal('84.950'), max_digits=10, null=True),
        ),
    ]
